# Generated by Django 2.1.7 on 2019-03-11 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tests', '0002_answer_question_results_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_auther',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tests.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='question_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tests.Test'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='results',
            name='completion_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='result_passer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='results',
            name='result_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Tests.Test'),
        ),
        migrations.AddField(
            model_name='results',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
